In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('heart.csv')

In [4]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [6]:
clf = GaussianNB()

In [7]:
X = data.iloc[:,0:13]
Y = data.iloc[:,-1]

In [8]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [9]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [11]:
Y_test

527    1
359    1
447    0
31     1
621    0
      ..
832    1
796    1
644    1
404    0
842    0
Name: target, Length: 205, dtype: int64

In [12]:
clf.fit(X_train, Y_train)

GaussianNB()

In [14]:
pred_prob = clf.predict_proba(X_test)
np.set_printoptions(suppress=True)
print('[scikit-learn] Predicted probabilities:\n', pred_prob)
# [['first column is "no disease" or 0', second column is "has disease" or 1]]

[scikit-learn] Predicted probabilities:
 [[0.00314519 0.99685481]
 [0.36444425 0.63555575]
 [0.99788133 0.00211867]
 [0.0016501  0.9983499 ]
 [0.99151223 0.00848777]
 [0.54861852 0.45138148]
 [0.99995446 0.00004554]
 [0.99998367 0.00001633]
 [0.0199339  0.9800661 ]
 [0.99993331 0.00006669]
 [0.00171561 0.99828439]
 [0.99999868 0.00000132]
 [0.00344513 0.99655487]
 [0.0696573  0.9303427 ]
 [0.99977996 0.00022004]
 [0.01169417 0.98830583]
 [0.99999528 0.00000472]
 [0.00079437 0.99920563]
 [0.13949231 0.86050769]
 [0.99994122 0.00005878]
 [0.01904079 0.98095921]
 [0.98774265 0.01225735]
 [0.32625021 0.67374979]
 [0.99985283 0.00014717]
 [0.01904079 0.98095921]
 [0.10444788 0.89555212]
 [0.00091219 0.99908781]
 [0.39588545 0.60411455]
 [0.99999792 0.00000208]
 [0.00807068 0.99192932]
 [0.88818601 0.11181399]
 [0.01864459 0.98135541]
 [0.29967586 0.70032414]
 [0.36444425 0.63555575]
 [0.00521109 0.99478891]
 [0.09066299 0.90933701]
 [0.01904079 0.98095921]
 [0.29536179 0.70463821]
 [0.22534848 0.77465152]
 [0.00215834 0.99784166]
 [0.99998367 0.00001633]
 [0.99463943 0.00536057]
 [0.33448573 0.66551427]
 [0.32625021 0.67374979]
 [0.99991037 0.00008963]
 [1.         0.        ]
 [0.98104156 0.01895844]
 [0.36313286 0.63686714]
 [0.04310791 0.95689209]
 [0.85730851 0.14269149]
 [0.02984143 0.97015857]
 [0.9999953  0.0000047 ]
 [0.05107387 0.94892613]
 [0.99997051 0.00002949]
 [0.00091219 0.99908781]
 [0.22534848 0.77465152]
 [0.93474762 0.06525238]
 [0.99995797 0.00004203]
 [0.01043028 0.98956972]
 [0.0106269  0.9893731 ]
 [0.74863315 0.25136685]
 [0.99533981 0.00466019]
 [0.99999792 0.00000208]
 [0.85730851 0.14269149]
 [0.99998275 0.00001725]
 [0.99768078 0.00231922]
 [0.00004963 0.99995037]
 [0.92946916 0.07053084]
 [1.         0.        ]
 [0.0007281  0.9992719 ]
 [0.06083806 0.93916194]
 [0.99999792 0.00000208]
 [0.40125638 0.59874362]
 [0.00689166 0.99310834]
 [0.26030359 0.73969641]
 [0.21965819 0.78034181]
 [0.99995446 0.00004554]
 [0.03154167 0.96845833]
 [0.18107149 0.81892851]
 [0.00583219 0.99416781]
 [0.58992488 0.41007512]
 [0.89194503 0.10805497]
 [0.99996418 0.00003582]
 [0.99995552 0.00004448]
 [0.08394452 0.91605548]
 [0.99997292 0.00002708]
 [0.00171561 0.99828439]
 [0.99431242 0.00568758]
 [0.58992488 0.41007512]
 [0.00807068 0.99192932]
 [0.37242981 0.62757019]
 [0.99994122 0.00005878]
 [0.06978758 0.93021242]
 [0.00237656 0.99762344]
 [0.07013008 0.92986992]
 [0.17210876 0.82789124]
 [0.92946916 0.07053084]
 [0.98983872 0.01016128]
 [0.99999999 0.00000001]
 [0.99875204 0.00124796]
 [0.31537436 0.68462564]
 [0.99448077 0.00551923]
 [0.10604541 0.89395459]
 [0.14397881 0.85602119]
 [0.97175414 0.02824586]
 [0.13351111 0.86648889]
 [0.99995797 0.00004203]
 [0.25104674 0.74895326]
 [0.32777689 0.67222311]
 [0.00112987 0.99887013]
 [0.01043028 0.98956972]
 [0.00112987 0.99887013]
 [0.00042413 0.99957587]
 [0.99919959 0.00080041]
 [0.05479222 0.94520778]
 [0.00191797 0.99808203]
 [0.99779833 0.00220167]
 [0.00323291 0.99676709]
 [0.00700294 0.99299706]
 [0.99996301 0.00003699]
 [0.15730565 0.84269435]
 [0.42273801 0.57726199]
 [0.99999199 0.00000801]
 [0.99083881 0.00916119]
 [0.96051348 0.03948652]
 [0.99985283 0.00014717]
 [0.02032977 0.97967023]
 [0.4205739  0.5794261 ]
 [0.06083806 0.93916194]
 [0.00419468 0.99580532]
 [0.01864459 0.98135541]
 [0.99999999 0.00000001]
 [0.00032823 0.99967177]
 [0.31537436 0.68462564]
 [0.99833472 0.00166528]
 [0.00071967 0.99928033]
 [0.99964402 0.00035598]
 [0.42273801 0.57726199]
 [0.00071967 0.99928033]
 [0.99779833 0.00220167]
 [0.0510797  0.9489203 ]
 [0.01818946 0.98181054]
 [0.000478   0.999522  ]
 [0.99938413 0.00061587]
 [0.07450804 0.92549196]
 [0.08423875 0.91576125]
 [0.02984143 0.97015857]
 [0.00371344 0.99628656]
 [0.69690587 0.30309413]
 [0.98765509 0.01234491]
 [0.29967586 0.70032414]
 [1.         0.        ]
 [0.09468754 0.90531246]
 [0.0510797  0.9489203 ]
 [0.96734743 0.03265257]
 [0.9870063  0.0129937 ]
 [0.45134827 0.54865173]
 [0.00419468 0.99580532]
 [0.99491225 0.00508775]
 [0.99463943 0.00536057]
 [0.33448573 0.66551427]
 [0.05067396 0.94932604]
 [0.99448077 0.00551923]
 [0.99448077 0.00551923]
 [0.99708813 0.00291187]
 [0.94454723 0.05545277]
 [0.93687753 0.06312247]
 [0.99834326 0.00165674]
 [0.99997711 0.00002289]
 [0.00371344 0.99628656]
 [0.40125638 0.59874362]
 [0.44383469 0.55616531]
 [0.05663572 0.94336428]
 [1.         0.        ]
 [0.00246883 0.99753117]
 [0.36444425 0.63555575]
 [0.00029353 0.99970647]
 [0.99999999 0.00000001]
 [0.10604541 0.89395459]
 [0.00469156 0.99530844]
 [0.00131653 0.99868347]
 [0.99994114 0.00005886]
 [0.00653886 0.99346114]
 [0.05107387 0.94892613]
 [0.07394275 0.92605725]
 [0.00700294 0.99299706]
 [0.00521109 0.99478891]
 [0.01043028 0.98956972]
 [0.18146009 0.81853991]
 [0.00341994 0.99658006]
 [0.00193952 0.99806048]
 [0.18107149 0.81892851]
 [0.01487102 0.98512898]
 [0.05107387 0.94892613]
 [0.99995797 0.00004203]
 [0.98460828 0.01539172]
 [0.0021843  0.9978157 ]
 [0.99999983 0.00000017]
 [0.00251862 0.99748138]
 [0.00078187 0.99921813]
 [0.1950885  0.8049115 ]
 [0.07524149 0.92475851]
 [0.00078187 0.99921813]
 [0.99782341 0.00217659]
 [0.91550052 0.08449948]]

In [15]:
pred = clf.predict(X_test)
print('[scikit-learn] Predicted probabilities:\n', pred)
# 0 == no disease
# 1 == has disease

[scikit-learn] Predicted probabilities:
 [1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 1 1
 1 1 0 1 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1
 1 1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 1 1 0 1 1 1 1
 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0]

In [16]:
from sklearn.metrics import classification_report
report = classification_report(Y_test, pred)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.71      0.78       102
           1       0.75      0.89      0.82       103

    accuracy                           0.80       205
   macro avg       0.81      0.80      0.80       205
weighted avg       0.81      0.80      0.80       205