In [1]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('heart.csv')

In [4]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [5]:
clf = MultinomialNB(force_alpha=True)

In [6]:
X = data.iloc[:,0:13]
Y = data.iloc[:,-1]

In [7]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [8]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [10]:
Y_test

527    1
359    1
447    0
31     1
621    0
      ..
832    1
796    1
644    1
404    0
842    0
Name: target, Length: 205, dtype: int64

In [11]:
clf.fit(X_train, Y_train)

MultinomialNB(force_alpha=True)

In [12]:
pred_prob = clf.predict_proba(X_test)
np.set_printoptions(suppress=True)
print('[scikit-learn] Predicted probabilities:\n', pred_prob)
# [['first column is "no disease" or 0', second column is "has disease" or 1]]

[scikit-learn] Predicted probabilities:
 [[0.00434735 0.99565265]
 [0.2567285  0.7432715 ]
 [0.99718941 0.00281059]
 [0.01063315 0.98936685]
 [0.92027355 0.07972645]
 [0.99754542 0.00245458]
 [0.99999267 0.00000733]
 [0.99968444 0.00031556]
 [0.00577602 0.99422398]
 [0.99081791 0.00918209]
 [0.17084369 0.82915631]
 [0.99997915 0.00002085]
 [0.02850593 0.97149407]
 [0.00003359 0.99996641]
 [0.99888801 0.00111199]
 [0.00544936 0.99455064]
 [0.99920731 0.00079269]
 [0.00000237 0.99999763]
 [0.00281086 0.99718914]
 [0.99845031 0.00154969]
 [0.68226117 0.31773883]
 [0.97918874 0.02081126]
 [0.46669157 0.53330843]
 [0.99998586 0.00001414]
 [0.68226117 0.31773883]
 [0.00110343 0.99889657]
 [0.16049353 0.83950647]
 [0.05008177 0.94991823]
 [0.99999953 0.00000047]
 [0.44863264 0.55136736]
 [0.73609705 0.26390295]
 [0.94329055 0.05670945]
 [0.0040245  0.9959755 ]
 [0.2567285  0.7432715 ]
 [0.00060984 0.99939016]
 [0.00452795 0.99547205]
 [0.68226117 0.31773883]
 [0.89592648 0.10407352]
 [0.35395271 0.64604729]
 [0.00031714 0.99968286]
 [0.99968444 0.00031556]
 [0.91865209 0.08134791]
 [0.06655883 0.93344117]
 [0.46669157 0.53330843]
 [0.99760067 0.00239933]
 [0.99997497 0.00002503]
 [0.57258103 0.42741897]
 [0.07856979 0.92143021]
 [0.00051613 0.99948387]
 [0.84356583 0.15643417]
 [0.4828252  0.5171748 ]
 [0.99991176 0.00008824]
 [0.03857605 0.96142395]
 [0.80272596 0.19727404]
 [0.16049353 0.83950647]
 [0.35395271 0.64604729]
 [0.88168742 0.11831258]
 [0.99781715 0.00218285]
 [0.00649284 0.99350716]
 [0.00121787 0.99878213]
 [0.00243698 0.99756302]
 [0.92120075 0.07879925]
 [0.99999953 0.00000047]
 [0.84356583 0.15643417]
 [0.99999675 0.00000325]
 [0.25473391 0.74526609]
 [0.00000259 0.99999741]
 [0.8105376  0.1894624 ]
 [0.99997497 0.00002503]
 [0.00221493 0.99778507]
 [0.00046991 0.99953009]
 [0.99999953 0.00000047]
 [0.04437709 0.95562291]
 [0.00122335 0.99877665]
 [0.23581891 0.76418109]
 [0.104026   0.895974  ]
 [0.99999267 0.00000733]
 [0.78386042 0.21613958]
 [0.39272111 0.60727889]
 [0.00881536 0.99118464]
 [0.05988478 0.94011522]
 [0.02841867 0.97158133]
 [0.99999709 0.00000291]
 [0.99988012 0.00011988]
 [0.55050395 0.44949605]
 [0.99999687 0.00000313]
 [0.17084369 0.82915631]
 [0.99375084 0.00624916]
 [0.05988478 0.94011522]
 [0.44863264 0.55136736]
 [0.0912009  0.9087991 ]
 [0.99845031 0.00154969]
 [0.00012219 0.99987781]
 [0.03301396 0.96698604]
 [0.00076026 0.99923974]
 [0.01296517 0.98703483]
 [0.8105376  0.1894624 ]
 [0.99944209 0.00055791]
 [0.99999868 0.00000132]
 [0.99954294 0.00045706]
 [0.99999491 0.00000509]
 [0.99988083 0.00011917]
 [0.09471217 0.90528783]
 [0.01679659 0.98320341]
 [0.60270578 0.39729422]
 [0.86021345 0.13978655]
 [0.99781715 0.00218285]
 [0.03422658 0.96577342]
 [0.37013609 0.62986391]
 [0.04008067 0.95991933]
 [0.00649284 0.99350716]
 [0.04008067 0.95991933]
 [0.00018978 0.99981022]
 [0.99494589 0.00505411]
 [0.02357066 0.97642934]
 [0.05118748 0.94881252]
 [0.07952775 0.92047225]
 [0.00421572 0.99578428]
 [0.00153515 0.99846485]
 [0.99999833 0.00000167]
 [0.9984324  0.0015676 ]
 [0.03281013 0.96718987]
 [0.99999467 0.00000533]
 [0.98982197 0.01017803]
 [0.76068649 0.23931351]
 [0.99998586 0.00001414]
 [0.00189888 0.99810112]
 [0.08276289 0.91723711]
 [0.00046991 0.99953009]
 [0.59046578 0.40953422]
 [0.94329055 0.05670945]
 [0.99999868 0.00000132]
 [0.00005868 0.99994132]
 [0.99999491 0.00000509]
 [0.9999571  0.0000429 ]
 [0.00007911 0.99992089]
 [0.99983083 0.00016917]
 [0.03281013 0.96718987]
 [0.00007911 0.99992089]
 [0.07952775 0.92047225]
 [0.0354573  0.9645427 ]
 [0.45189157 0.54810843]
 [0.03270636 0.96729364]
 [0.9998901  0.0001099 ]
 [0.8872583  0.1127417 ]
 [0.00005287 0.99994713]
 [0.4828252  0.5171748 ]
 [0.02265029 0.97734971]
 [0.79420896 0.20579104]
 [0.99905023 0.00094977]
 [0.0040245  0.9959755 ]
 [0.99997497 0.00002503]
 [0.21232065 0.78767935]
 [0.0354573  0.9645427 ]
 [0.99478592 0.00521408]
 [0.97338106 0.02661894]
 [0.37579816 0.62420184]
 [0.59046578 0.40953422]
 [0.99998068 0.00001932]
 [0.91865209 0.08134791]
 [0.06655883 0.93344117]
 [0.60872858 0.39127142]
 [0.99988083 0.00011917]
 [0.99988083 0.00011917]
 [0.53498146 0.46501854]
 [0.99995067 0.00004933]
 [0.64180764 0.35819236]
 [0.99999806 0.00000194]
 [0.98325034 0.01674966]
 [0.02265029 0.97734971]
 [0.04437709 0.95562291]
 [0.0822328  0.9177672 ]
 [0.7821728  0.2178272 ]
 [0.99925735 0.00074265]
 [0.02433299 0.97566701]
 [0.2567285  0.7432715 ]
 [0.00000093 0.99999907]
 [0.99999941 0.00000059]
 [0.09471217 0.90528783]
 [0.00465333 0.99534667]
 [0.00012949 0.99987051]
 [0.99586086 0.00413914]
 [0.03455125 0.96544875]
 [0.03857605 0.96142395]
 [0.67093267 0.32906733]
 [0.00153515 0.99846485]
 [0.00060984 0.99939016]
 [0.00649284 0.99350716]
 [0.01691628 0.98308372]
 [0.36078185 0.63921815]
 [0.03955708 0.96044292]
 [0.39272111 0.60727889]
 [0.00035334 0.99964666]
 [0.03857605 0.96142395]
 [0.99781715 0.00218285]
 [0.91548885 0.08451115]
 [0.00364735 0.99635265]
 [0.99998449 0.00001551]
 [0.00004131 0.99995869]
 [0.0001703  0.9998297 ]
 [0.60135643 0.39864357]
 [0.0417921  0.9582079 ]
 [0.0001703  0.9998297 ]
 [0.97547864 0.02452136]
 [0.07096093 0.92903907]]

In [13]:
pred = clf.predict(X_test)
print('[scikit-learn] Predicted probabilities:\n', pred)
# 0 == no disease
# 1 == has disease

[scikit-learn] Predicted probabilities:
 [1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 0
 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1 1
 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1
 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 1 1 1
 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0
 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1]

In [14]:
from sklearn.metrics import classification_report
report = classification_report(Y_test, pred)
print(report)

              precision    recall  f1-score   support

           0       0.70      0.65      0.67       102
           1       0.68      0.73      0.70       103

    accuracy                           0.69       205
   macro avg       0.69      0.69      0.69       205
weighted avg       0.69      0.69      0.69       205